### PR TITLE
Add examples

### PR DESCRIPTION
**Pull request by Charliekenney23**
Hey!

I'm a big fan of React Stack Grid. I'm learning VueJS at the moment and I thought I'd offer to contribute to this repo as I'm in need of a more advanced grid for a Vue project I'm working on. Thought I should start with this and work on animations and cloning [this](https://tsuyoshiwada.github.io/react-stack-grid/#/), this weekend. Please let me know if I can help in any way.

Thanks,
Charles

### CODE REVIEW

**Comment by WouterFlorijn** [comment]
Great! I'll check this out as soon as I have some spare time. Feel free to contribute more whenever you see new opportunities. Would be great to create a more full-fledged stack grid for Vue, (I'm a fan of react-stack-grid too). I haven't made a huge amount of npm packages/open source projects, so I'm just learning as I go along.

**Comment by WouterFlorijn** [comment]
I changed up the script a bit to make it run on Windows. I think it should still work elsewhere but let me know if it doesn't.

**Comment by Charliekenney23** [comment]
Sweet thanks for the merge, hopefully I'll get around to cloning the react example this weekend. Yeah seems to be throwing `module not found` for me, because it's attempting to resolve the module at `vue-stack-grid/simple` instead of `vue-stack-grid/examples/simple`. Maybe the best thing would be to use my method for POSIX and yours for windows via `process.platform`. I will submit a PR for this

**Comment by WouterFlorijn** [comment]
@Charliekenney23 Yes for now that should be fine. Maybe there's a more elegant way but this works.

**Pull request merged**
